### ISSUE TITLE
AdonisJS 6

### ISSUE THREAD

**Issue by timganter** [Julien-R44/adonisjs-prometheus#11]
👋🏼 does this work with AdonisJs v6? If not, any plans to upgrade it?

**Comment by Julien-R44** [comment]
Hey, yes I rewrote the package for version 6 on the `next` branch a while ago: https://github.com/Julien-R44/adonisjs-prometheus/commits/next/ 

I intended to add new features before releasing the new version. But I didn't have the time. And I admit that this package isn't at the top of my priority list at the moment, but it's still planned

**Comment by timganter** [comment]
Ah ha! Cool! 🙇 

I'll keep an eye on it. At the moment, this package is the primary reason we haven't upgraded to 6 yet. It's not urgent for us at the moment but might become more pressing in the upcoming months.

**Comment by Julien-R44** [comment]
Maybe you can ask your company to sponsor me so I will be able to release it more quickly. Win-win situation 😄

**Comment by hkmsadek** [comment]
Ok, let's sponsor [Julien](https://github.com/Julien-R44)

**Comment by Julien-R44** [comment]
A new version for AdonisJS 6 has been released. Make sure to check the readme file to see the new changes!
