### ISSUE TITLE
Allow function to evaluate excluded routes in config

### ISSUE THREAD

**Issue by arthur-er** [Julien-R44/adonisjs-prometheus#7]
Allow a boolean returning function to evaluate excluded routes (like in [Adonis Shield](https://docs.adonisjs.com/guides/security/web-security#configuration)).

If approved, I'm willing to help implement this.

**Comment by Julien-R44** [comment]
Hey thanks for the suggestion! I will make a new release asap

**Comment by Julien-R44** [comment]
Released in 0.0.6👍
